In [11]:
#a.Импортируйте библиотеку NumPy
import numpy as np

In [3]:
#b.Создайте массив из 10 нулей

a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#c.Создать массив из 10 единиц

b = np.ones((1, 10), dtype='int')
print(b)

[[1 1 1 1 1 1 1 1 1 1]]


In [ ]:
#d.Создать массив из 10 пятерок

c = np.full((1,10), 5)
print(c)

[[5 5 5 5 5 5 5 5 5 5]]


In [7]:
#e.Создать массив из целых чисел от 10 до 50

d = np.arange(10,51)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [8]:
#f.Создать массив из четных чисел от 10 до 50

e = np.arange(10,51,2)
print(e)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [9]:
#g.Создать матрицу 3х3 с числами от 0 до 8

f = np.array ([[0,1,2], [3,4,5], [6,7,8]])
print (f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#h.Создать единичную матрицу 3x3

e = np.ones((3, 3), dtype='int')
print(e)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
#i.Используйте NumPy для генерации случайного числа от 0 до 1

f = np.random.rand ()
print(f)

0.21965822472771257


In [18]:
#j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

g = np.random.randn (1,25)
print(g)

[[-1.12904668e+00  3.94725159e-01  3.20727681e-01 -6.09111073e-01
  -7.14024022e-04  5.33472646e-01  7.20909655e-01 -7.27476090e-01
   1.08902912e-01 -5.59327692e-01  7.73990940e-01  1.70821771e-02
   1.97572977e-01  2.24831699e-01  2.78291903e-01  1.83842527e+00
  -3.51896858e-01 -5.25957316e-01  6.33414072e-01  9.38077863e-01
  -3.42075659e-03 -3.40394651e-01  2.79240288e-01 -1.73595304e+00
   1.13440491e+00]]


In [60]:
#k.Создайте следующую матрицу используя функции библиотеки NumPy

h = np.arange(0.01,1.01,0.01)
h = h.reshape(10,10)
print (h)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [24]:
# это наша стартовая матрица

mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [66]:
# l.Необходимо написать код который вернет следующую матрицу из стартовой

mat = np.arange(1,26).reshape(5,5)
i = mat[2:,1:]
print(i)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [68]:
#m.Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l

mat = np.arange(1,26).reshape(5,5)
print(mat[3,4])

20


In [72]:
#n.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

mat = np.arange(1,26).reshape(5,5)
j = mat[0:3,1]
k = j.reshape(3,1)

print(k)


[[ 2]
 [ 7]
 [12]]


In [74]:
#o.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

mat = np.arange(1,26).reshape(5,5)
l = mat[4:,0:]

print(l)


[[21 22 23 24 25]]


In [75]:
#p.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

mat = np.arange(1,26).reshape(5,5)
m = mat[3:,0:]

print(m)


[[16 17 18 19 20]
 [21 22 23 24 25]]


In [76]:
#q.Получить сумму всех значений в стартовой матрице mat

mat = np.arange(1,26).reshape(5,5)
print(mat.sum())

325


In [80]:
#r.Получить стандартное отклонение в стартовой матрице mat

mat = np.arange(1,26).reshape(5,5)
print(mat.std())

7.211102550927978


In [79]:
#s.Получить сумму значений в колонках в стартовой матрице mat

mat = np.arange(1,26).reshape(5,5)
print(mat.sum(axis=1))

[ 15  40  65  90 115]
